---
jobs:
  - name: job
    public: true
    plan:
      - task: first-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: echo
            args: ["Hello, first!"]

      - task: second-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
          run:
            path: echo
            args: ["Hello, second!"]

